# Generated by Django 2.2.4 on 2020-05-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre', max_length=30)),
                ('modelo', models.CharField(max_length=30, null=True)),
                ('descripcion', models.CharField(max_length=30, null=True)),
                ('token', models.CharField(max_length=50, null=True)),
                ('activo', models.BooleanField(default=1)),
            ],
        ),
    ]
