# Generated by Django 3.0.6 on 2020-05-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivos',
            name='activo',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='descripcion',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='modelo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=30),
        ),
    ]
